This is makeindex, version 2.15 [MiKTeX 2.9.7250 64-bit] (kpathsea + Thai support).
Scanning style file ./User_Guide.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file User_Guide.acn....done (45 entries accepted, 0 rejected).
Sorting entries....done (250 comparisons).
Generating output file User_Guide.acr....done (33 lines written, 0 warnings).
Output written in User_Guide.acr.
Transcript written in User_Guide.alg.
